# Generated by Django 5.2.6 on 2025-10-16 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_genero_libros_generos'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallesLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumen', models.TextField()),
                ('portada_url', models.CharField()),
                ('lenguaje', models.CharField()),
                ('libro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='libreria.libros')),
            ],
        ),
    ]
