# Generated by Django 5.2.7 on 2025-10-20 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_prestamo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recomendacion_at', models.DateTimeField(auto_now_add=True)),
                ('nota', models.TextField(blank=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.libros')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'libro')},
            },
        ),
        migrations.AddField(
            model_name='libros',
            name='recomendacion_by',
            field=models.ManyToManyField(related_name='libros_recomendados', through='libreria.Recomendaciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
